export const HEADINGS_COLLECTED = 'HEADINGS_COLLECTED';
export const HEADINGS_REQUESTED = 'HEADINGS_REQUESTED';
export const HEADING_PRESSED = 'HEADING_PRESSED';

export const LINKS_COLLECTED = 'LINKS_COLLECTED';
export const LINKS_REQUESTED = 'LINKS_REQUESTED';
